import { Open_Sans } from "next/font/google";
import "./globals.css";

const open_Sans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${open_Sans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}